"""gateway control plane baseline

Revision ID: 20260720_01
Revises:
Create Date: 2026-07-20
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "20260720_01"
down_revision = None
branch_labels = None
depends_on = None

UUID = postgresql.UUID(as_uuid=True)
JSONB = postgresql.JSONB(astext_type=sa.Text())


def upgrade() -> None:
    op.create_table("users", sa.Column("id", UUID, primary_key=True), sa.Column("username", sa.String(64), nullable=False, unique=True), sa.Column("role", sa.String(16), nullable=False), sa.Column("display_name", sa.String(64), nullable=False), sa.Column("password_hash", sa.String(256), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("devices", sa.Column("id", UUID, primary_key=True), sa.Column("code", sa.String(32), nullable=False, unique=True), sa.Column("name", sa.String(64), nullable=False), sa.Column("type", sa.String(32), nullable=False), sa.Column("model", sa.String(64)), sa.Column("capabilities", JSONB, nullable=False), sa.Column("section_tags", JSONB, nullable=False), sa.Column("permissions", JSONB, nullable=False), sa.Column("status", sa.String(16), nullable=False), sa.Column("battery", sa.Float(), nullable=False), sa.Column("position_x", sa.Float(), nullable=False), sa.Column("position_y", sa.Float(), nullable=False), sa.Column("position_z", sa.Float(), nullable=False), sa.Column("section_id", sa.String(32)), sa.Column("registered_at", sa.DateTime(timezone=True), nullable=False), sa.Column("last_heartbeat", sa.DateTime(timezone=True)), sa.Column("health", JSONB, nullable=False), sa.Column("gateway_enabled", sa.Boolean(), nullable=False), sa.Column("gateway_key_hash", sa.String(128)), sa.Column("gateway_key_rotated_at", sa.DateTime(timezone=True)))
    op.create_table("scripts", sa.Column("id", UUID, primary_key=True), sa.Column("name", sa.String(64), nullable=False), sa.Column("description", sa.Text()), sa.Column("stage", sa.String(32), nullable=False), sa.Column("config", JSONB, nullable=False), sa.Column("is_active", sa.Boolean(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("map_regions", sa.Column("id", UUID, primary_key=True), sa.Column("code", sa.String(32), nullable=False, unique=True), sa.Column("name", sa.String(64), nullable=False), sa.Column("region_type", sa.String(32), nullable=False), sa.Column("polygon", JSONB, nullable=False), sa.Column("stage", sa.String(32)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("map_points", sa.Column("id", UUID, primary_key=True), sa.Column("code", sa.String(32), nullable=False, unique=True), sa.Column("name", sa.String(64), nullable=False), sa.Column("point_type", sa.String(32), nullable=False), sa.Column("x", sa.Float(), nullable=False), sa.Column("y", sa.Float(), nullable=False), sa.Column("z", sa.Float(), nullable=False), sa.Column("process_type", sa.String(32)), sa.Column("device_types", JSONB, nullable=False), sa.Column("stage", sa.String(32)))
    op.create_table("tasks", sa.Column("id", UUID, primary_key=True), sa.Column("code", sa.String(32), nullable=False, unique=True), sa.Column("name", sa.String(128), nullable=False), sa.Column("process_id", sa.String(32), nullable=False), sa.Column("script_id", UUID, sa.ForeignKey("scripts.id")), sa.Column("device_id", UUID, sa.ForeignKey("devices.id")), sa.Column("map_point_id", UUID, sa.ForeignKey("map_points.id")), sa.Column("status", sa.String(16), nullable=False), sa.Column("priority", sa.Integer(), nullable=False), sa.Column("progress", sa.Float(), nullable=False), sa.Column("dependencies", JSONB, nullable=False), sa.Column("params", JSONB, nullable=False), sa.Column("estimated_duration", sa.Integer(), nullable=False), sa.Column("planned_start", sa.DateTime(timezone=True)), sa.Column("planned_end", sa.DateTime(timezone=True)), sa.Column("started_at", sa.DateTime(timezone=True)), sa.Column("completed_at", sa.DateTime(timezone=True)), sa.Column("deliverable_qty", sa.Float()), sa.Column("deliverable_unit", sa.String(32)), sa.Column("completed_qty", sa.Float(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("stage", sa.String(32), nullable=False))
    op.create_table("mission_executions", sa.Column("id", UUID, primary_key=True), sa.Column("task_id", UUID, sa.ForeignKey("tasks.id"), nullable=False), sa.Column("device_id", UUID, sa.ForeignKey("devices.id"), nullable=False), sa.Column("gateway_execution_id", sa.String(96), nullable=False, unique=True), sa.Column("state", sa.String(24), nullable=False), sa.Column("progress", sa.Float(), nullable=False), sa.Column("completed_qty", sa.Float()), sa.Column("result", JSONB, nullable=False), sa.Column("failure_code", sa.String(96)), sa.Column("dispatched_at", sa.DateTime(timezone=True), nullable=False), sa.Column("accepted_at", sa.DateTime(timezone=True)), sa.Column("started_at", sa.DateTime(timezone=True)), sa.Column("completed_at", sa.DateTime(timezone=True)), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("device_commands", sa.Column("id", UUID, primary_key=True), sa.Column("device_id", UUID, sa.ForeignKey("devices.id"), nullable=False), sa.Column("command", sa.String(32), nullable=False), sa.Column("payload", JSONB, nullable=False), sa.Column("idempotency_key", sa.String(128), nullable=False, unique=True), sa.Column("source", sa.String(32), nullable=False), sa.Column("priority", sa.Integer(), nullable=False), sa.Column("expires_at", sa.DateTime(timezone=True)), sa.Column("delivery_attempts", sa.Integer(), nullable=False), sa.Column("last_delivered_at", sa.DateTime(timezone=True)), sa.Column("mission_execution_id", UUID, sa.ForeignKey("mission_executions.id")), sa.Column("status", sa.String(16), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("delivered_at", sa.DateTime(timezone=True)), sa.Column("acknowledged_at", sa.DateTime(timezone=True)), sa.Column("acknowledgement", JSONB, nullable=False))
    op.create_table("device_events", sa.Column("time", sa.DateTime(timezone=True), primary_key=True), sa.Column("device_id", UUID, sa.ForeignKey("devices.id"), primary_key=True), sa.Column("event_type", sa.String(32), nullable=False), sa.Column("event_id", sa.String(96)), sa.Column("boot_id", sa.String(96)), sa.Column("sequence", sa.Integer()), sa.Column("received_at", sa.DateTime(timezone=True), nullable=False), sa.Column("payload", JSONB, nullable=False), sa.UniqueConstraint("device_id", "event_id", name="uq_device_events_device_event_id"))
    op.create_table("alerts", sa.Column("id", UUID, primary_key=True), sa.Column("device_id", UUID, sa.ForeignKey("devices.id")), sa.Column("level", sa.String(16), nullable=False), sa.Column("category", sa.String(32), nullable=False), sa.Column("message", sa.Text(), nullable=False), sa.Column("status", sa.String(16), nullable=False), sa.Column("payload", JSONB, nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("resolved_at", sa.DateTime(timezone=True)))
    op.create_table("safety_states", sa.Column("scope", sa.String(32), primary_key=True), sa.Column("active", sa.Boolean(), nullable=False), sa.Column("cycle_id", sa.String(96)), sa.Column("source", sa.String(64)), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("cameras", sa.Column("id", UUID, primary_key=True), sa.Column("code", sa.String(32), nullable=False, unique=True), sa.Column("name", sa.String(64), nullable=False), sa.Column("location", sa.String(128), nullable=False), sa.Column("position_x", sa.Float(), nullable=False), sa.Column("position_y", sa.Float(), nullable=False), sa.Column("is_online", sa.Boolean(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("camera_detections", sa.Column("id", UUID, primary_key=True), sa.Column("camera_id", UUID, sa.ForeignKey("cameras.id"), nullable=False), sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False), sa.Column("excavator_count", sa.Integer(), nullable=False), sa.Column("truck_count", sa.Integer(), nullable=False), sa.Column("person_count", sa.Integer(), nullable=False), sa.Column("dust_level", sa.String(16), nullable=False), sa.Column("slope_risk", sa.String(16), nullable=False), sa.Column("ai_compliance_rate", sa.Float(), nullable=False))
    for table, column in (("devices", "code"), ("devices", "type"), ("devices", "status"), ("devices", "last_heartbeat"), ("tasks", "status"), ("tasks", "process_id"), ("mission_executions", "task_id"), ("mission_executions", "device_id"), ("device_commands", "device_id"), ("device_commands", "command"), ("device_commands", "status"), ("alerts", "device_id"), ("alerts", "level"), ("alerts", "category"), ("alerts", "status"), ("device_events", "event_type"), ("device_events", "received_at"), ("camera_detections", "camera_id"), ("camera_detections", "detected_at")):
        op.create_index(f"ix_{table}_{column}", table, [column])


def downgrade() -> None:
    for table in ("camera_detections", "cameras", "safety_states", "alerts", "device_events", "device_commands", "mission_executions", "tasks", "map_points", "map_regions", "scripts", "devices", "users"):
        op.drop_table(table)
